services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=pismo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pismo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pismo -d pismo_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pismo-api:
    container_name: pismo-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CONFIG_PATH=/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
#      interval: 30s
#      timeout: 3s
#      start_period: 10s
#      retries: 3
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro

volumes:
  postgres-data:

