services:
  postgres:
    container_name: postgres
    image: postgres:115-alpine
    environment:
      - POSTGRES_USER=pismo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=pismo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pismo -d pismo_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
