app:
  env: "development"
  address: ":8080"
  loglevel: "debug"

database:
  dsn: "postgres://pismo:123456@postgres:5432/pismo_db?sslmode=disable"
#  dsn: "postgres://pismo:123456@localhost:5432/pismo_db?sslmode=disable"

