app:
  env: "development"
  address: ":8080"
  log_level: "debug"

database:
  url: "postgres://user:password@localhost:5432/database?sslmode=disable"

cache:
  url: "redis://localhost:6379/0"

distributed_lock:
  ttl_ms: 5000
  retry_interval_ms: 2000
  waiting_time_ms: 4500